Kelompok1/urls.py
from django.contrib import admin
from django.urls import path, include
from crowdfunding.views import daftar

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('homePage.urls')),
    path('crowd/', include(('crowdfunding.urls', 'crowdfunding'), namespace = "crowdfunding")),
    path('viewmore/', include('viewmore.urls'))
]

crowdfunding/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.daftar, name = 'daftar'),
	path('daftar', views.daftar, name = 'daftar'),
	path('terdaftar', views.savedata, name = 'terdaftar'),
	path('donasi', views.donasi, name = 'donasi'),
	path('terdonasi', views.savedatadonasi, name = 'terdonasi'),

]

homePage/urls.py
from django.urls import path
from homePage import views

urlpatterns = [
    path('', views.home,  name="home"),
]

viewmore/urls.py
from django.urls import path
from .views import index, viewnews, viewprogram

urlpatterns = [
    path('', index, name='index'),
    path('berita', viewnews, name= 'news'),
    path('program', viewprogram, name= 'program')
]

crowdfunding/models.py
from django.db import models
from django.utils import timezone
from datetime import date
# Create your models here.
class Model_Daftar(models.Model):
	nama = models.CharField(max_length=200)
	tanggal_lahir = models.DateField(max_length=200)
	email = models.EmailField(unique = True)
	password = models.CharField(max_length = 200)
	

class Model_Donasi(models.Model):
	nama_program = models.CharField(max_length=200)
	nama = models.CharField(max_length = 200)
	email = models.EmailField()
	jumlah = models.IntegerField()
	
def __str__(self):
	return self.nama

viewmore/models.py
from django.db import models

# Create your models here.
class Program(models.Model):
	title = models.CharField(max_length=50)
	terkumpul = models.IntegerField()

class Berita(models.Model):
	title = models.CharField(max_length=50)
	paragraph = models.CharField(max_length=1000)

crowdfunding/forms.py
from django import forms
import datetime
class Form_Daftar(forms.Form):

    error_messages = {
        'required': 'Please type',
    }

    nama_attrs = {
        'type': 'text',
        'placeholder' : 'Nama Lengkap',
        'class' : 'form-control',
    }

    tanggal_lahir_attrs = {
        'type': 'date',
        'placeholder' : 'Tanggal Lahir',
        'class' : 'form-control',
    }

    email_attrs = {
        'type': 'email',
        'placeholder' : 'Email',
        'class' : 'form-control',
    }

    password_attrs = {
        'type': 'password',
        'placeholder': 'Password',
        'class' : 'form-control'
    }

    nama = forms.CharField(label='Nama Lengkap', required=True, widget=forms.TextInput(attrs = nama_attrs))
    tanggal_lahir = forms.DateField(label='Tanggal Lahir', required=True, widget=forms.DateInput(attrs = tanggal_lahir_attrs))
    email = forms.EmailField(label='Alamat Email', required=True, widget=forms.TextInput(attrs = email_attrs))
    password = forms.CharField(required=True, widget = forms.PasswordInput(attrs = password_attrs))

class Form_Donasi(forms.Form):
    error_messages = {
        'required': 'Please type',
    }

    nama_program_attrs = {
        'type': 'text',
        'placeholder' : 'Nama Program',
        'class' : 'form-control',
    }

    nama_attrs = {
        'type': 'text',
        'placeholder' : 'Nama Lengkap',
        'class' : 'form-control',
    }

    email_attrs = {
        'type': 'email',
        'placeholder' : 'Email',
        'class' : 'form-control',
    }

    jumlah_attrs = {
        'type': 'number',
        'placeholder': 'Jumlah Donasi',
        'class' : 'form-control',
    }

    nama_program = forms.CharField(label='Nama Program', required=True, widget=forms.TextInput(attrs = nama_program_attrs))
    nama = forms.CharField(label='Nama Lengkap', required=True, widget=forms.TextInput(attrs = nama_attrs))
    email = forms.EmailField(label='Alamat Email', required=True, widget=forms.TextInput(attrs = email_attrs))
    jumlah = forms.IntegerField(required=True, widget = forms.NumberInput(attrs = jumlah_attrs))

homePage/forms.py
from django import forms
from .models import Jadwal
from django.forms import ModelForm

class Message_Form(ModelForm):
	class Meta:
		model = Jadwal
		fields = ['Kegiatan','tempat','kategori','tanggal','waktu']

crowdfunding/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Form_Daftar, Form_Donasi
from .models import Model_Daftar, Model_Donasi

response = {}

# Create your views here.

def daftar(request):
	response['form_daftar'] = Form_Daftar
	html = "formdaftar.html"
	response['errmsg'] = ''
	return render(request, html, response)

def savedata(request):
	form = Form_Daftar(request.POST or None)
	if (request.method == 'POST' and form.is_valid()):
		response['nama'] = request.POST['nama']
		response['tanggal_lahir'] = request.POST['tanggal_lahir']
		response['email'] = request.POST['email']
		response['password'] = request.POST['password']
		project = Model_Daftar(nama = response['nama'], tanggal_lahir = response['tanggal_lahir'], email = response['email'], password = response['password'])
			
		data = Model_Daftar.objects.all().filter(email = response['email']).count()

		if data == 0:
			project.save()
			project = Model_Daftar.objects.all()
			response['project'] = project
			html = 'terdaftar.html'
			return render (request, html, response)
		else:
			response['errmsg'] = 'email sudah terdaftar'
			html = 'formdaftar.html'
			return render (request, html, response)
	else:
		response['form_daftar'] = Form_Daftar
		response['errmsg']='input tidak valid'
		html = "formdaftar.html"
		return render(request, html, response)

def donasi(request):
	response['form_donasi'] = Form_Donasi
	response['errmsg']=''
	html = "formdonasi.html"
	return render(request, html, response)

def savedatadonasi(request):
	form = Form_Donasi(request.POST or None)
	if (request.method == 'POST' and form.is_valid()):
		response['nama_program'] = request.POST['nama_program']
		response['nama'] = request.POST['nama']
		response['email'] = request.POST['email']
		response['jumlah'] = request.POST['jumlah']
		project = Model_Donasi(nama_program = response['nama_program'], nama = response['nama'], email = response['email'], jumlah = response['jumlah'])
		project.save()
		project = Model_Donasi.objects.all()
		response['project'] = project
		html = 'terdonasi.html'
		response['msg']='sudah donasi'
		return render (request, html, response)
	else:
		response['form_donasi'] = Form_Donasi
		response['errmsg']='input tidak valid'
		html = "formdonasi.html"
		return render(request, html, response)

homePage/views.py
from django.shortcuts import render
from viewmore.models import Berita, Program

# Create your views here.
def home(request):
	news = Berita.objects.all().values()
	temp = []
	progs = Program.objects.all().values()
	temp2 = []
	html = 'homePage.html'
	

	if news.count() == 0:
		return render(request, html)
	elif news.count() >= 4:
		for x in range(4):
			temp.append(news[x])

	elif progs.count() >= 6:
		for x in range(6):
			temp2.append(progs[x])
	else:
		for x in range(news.count()):
			temp.append(news[x])
		for x in range(progs.count()):
			temp2.append(progs[x])
	

	response = {'progs': temp2, 'news' : temp }
	
	return render(request, html, response)

viewmore/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Berita, Program

# Create your views here.
def index(request):
    return HttpResponse("Hello Mamank")

def viewnews(request):
	news = Berita.objects.all().values()
	response = {'news': news}
	html = 'htmlview.html'
	return render(request, html, response)

def viewprogram(request):
	progs = Program.objects.all().values()
	response = {'progs': progs}
	html = 'htmlview2.html'
	return render(request, html, response)
	

crowdfunding/templates/footer.html
<footer class="container-fluid footer" style="
background-color: #277091; 
color: white; 
padding-left:100px;
padding-right: 100px;
font-size: 25px;
font-weight: 100;
">
<br>
  <div class="row">
    <div class="col-sm-7">
      <h4><b>FUNDEE</b></h4>
    </div>
    <div class="col-sm-2.5" style="padding-top: 7px">
      <p>Our Social Media :</p>
    </div>
    <div class="col-sm">
      <a href="#" class="fa fa-facebook"></a>
      <a href="#" class="fa fa-twitter"></a>
      <a href="#" class="fa fa-google"></a>
      <a href="#" class="fa fa-linkedin"></a>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-7">
      <p> 
        <b style=" color: #69DBE2">Fundee</b> adalah platform untuk<br>
        menggalang dana dan<br>
        berdonasi secara online dan<br>
        transparan.
      </p>
    </div>
    <div class="col-sm-5.5" style="font-size: 20px; padding-top: 5px;">
      Meet our team :)<br>
      Naufaldi Athallah Rifqi as <b>CEO</b><br>
      Dimas Aditya Faiz as <b>CTO</b><br>
      Azhar Difa Arnanda as <b>FrontEnd Prgrammer</b><br>
      Faishal Ridwan as <b>BackEnd Programmer</b>
    </div>  
  </div>
  <p style="color: #69DBE2">Fakultas Ilmu Komputer<br>Universitas Indonesia</p>
  <br>
</footer>



    

crowdfunding/templates/formdaftar.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>FUNDEE</title>
	<link rel="stylesheet" type="text/css" href="{%static 'stylesheet.css' %}"/>
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

	{% include "navbar.html" %}
</head>
<body>
<section>
	<br>
  <div>
        <div style="width: 30%; margin: auto;" class = "jumbotron">
        	<div class="row" style="background-color: #DBF2FF">
        	<h1 style="font-family: niramit; text-align: center; font-size: 40px" >Welcome to FUNDEE!</h1>
        	<br>
        	</div>
        	<br>
            <form id="form" method="POST" action="{% url 'crowdfunding:terdaftar' %}">
            {% csrf_token %}
            {{ form_daftar.as_p }}
            <input id="submit" type="submit" class="btn btn-lg btn-info" value="Sign Up">
            <p>{{errmsg}}</p>
          </form>
        </div>
    </div>

</section>
    <br><br><br><br><br>
    {% include "footer.html" %}
</body>
</html>

crowdfunding/templates/formdonasi.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>Sinar Perak</title>
  <link rel="stylesheet" type="text/css" href="{%static 'stylesheet.css' %}"/>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  
  {% include "navbar.html" %}
</head>
<body>

<br>
<section>
  <div>
        <div style="width: 30%; margin: auto;" class = "jumbotron">
          <div class="row" style="background-color: #DBF2FF">
          <h1 style="font-family: niramit; text-align: center; font-size: 40px;">Donasi</h1>
          <br>
          </div>
          <br>
          <form id="form" method="POST" action="{% url 'crowdfunding:terdonasi' %}">
            {% csrf_token %}
            {{ form_donasi.as_p }}
            <input id="submit" type="submit" class="btn btn-lg btn-info" value="Submit">
            <p>{{errmsg}}</p>
          </form>
          <a href="/" class="btn btn-default">Kembali</a>
        </div>
    </div>

</section>
<br><br><br><br><br>
{% include "footer.html" %}
</body>
    
</html>

crowdfunding/templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #277091;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 30px;
    text-decoration: none;
}

li a:hover:not(.active) {
    background-color: #111;
}

.active {
    background-color: #4CAF50;
}
</style>
</head>
<body>

<ul>
  <li><a href="/">Home</a></li>
  <li><a href="/viewmore/berita">Berita</a></li>
  <li><a href="/viewmore/program">Program</a></li>
  <li style="float:right"><a class="active" href="/crowd/daftar">Daftar</a></li>
  <li style="float:right"><a class="active" href="/crowd/donasi">Donasi</a></li>
</ul>

</body>
</html>

crowdfunding/templates/terdaftar.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>
<body>
<h1>Anda sudah terdaftar</h1>
<a href="/home" class="w3-button w3-black">Home Page</a>
</body>
</html>

crowdfunding/templates/terdonasi.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<h1>{{msg}}</h1>
</body>
</html>

homePage/templates/footer.html
<footer class="container-fluid footer navbar-fixed-bottom" style="
background-color: #277091; 
color: white; 
padding-left:100px;
padding-right: 100px;
font-size: 25px;
font-weight: 100;
">
<br>
  <div class="row">
  	<div class="col-sm-5">
  		<h4><b>FUNDEE</b></h4>
  	</div>
  	<div class="col-sm-3" style="padding-top: 7px">
  		<p>Our Social Media :</p>
  	</div>
  	<div class="col-sm">
  		<a href="#" class="fa fa-facebook"></a>
  		<a href="#" class="fa fa-twitter"></a>
  		<a href="#" class="fa fa-google"></a>
  		<a href="#" class="fa fa-linkedin"></a>
  	</div>
  </div>
  <div class="row">
  	<div class="col-sm-5">
  		<p> 
  			<b style=" color: #69DBE2">Fundee</b> adalah platform untuk<br>
  			menggalang dana dan<br>
  			berdonasi secara online dan<br>
  			transparan.
  		</p>
  	</div>
  	<div class="col-sm-3" style="font-size: 20px; padding-top: 5px;">
  		Meet our team :)<br>
  		Naufaldi Athallah Rifqi as <b>CEO</b><br>
  		Dimas Aditya Faiz as <b>CTO</b><br>
  		Azhar Difa Arnanda as <b>FrontEnd Prgrammer</b><br>
  		Faishal Ridwan as <b>BackEnd Programmer</b>
  	</div>	
  </div>
  <p style="color: #69DBE2">Fakultas Ilmu Komputer<br>Universitas Indonesia</p>
  <br>
</footer>



		

homePage/templates/homePage.html
{% load static %}
<!DOCTYPE Html>
<html>
	<head>
		<link rel="stylesheet" type="text/css" href={% static 'css/mystyle.css' %}>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1" >
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	
		{% include "navbar.html" %}
	</head>

	<body>
		<div class="header">
		
			<div class="getStarted">
				<h1 class="display-4">
					No one has ever<br>become poor by<br>giving.<br>
				</h1>
				<p style="font-size: 20px">
					Get Started Today<br>
				</p>
				<form method="get" action="/crowd/donasi">
    				<button class="button" style="vertical-align:middle;"><span>Fundee now</span></button>
				</form>
			</div>
		</div>

		<div class="berita" style="background-color: #277091">
			<br><br>
			<div class="container">
				<h2 style="color: white">BERITA</h2>
				<div class="card-deck">
					{% for e in news%}

					<div class="card shadow-card" style="width:200px">
						<img class="card-img-top" src="/static/images/bencana.jpg" alt="bencana" style="width:100%">
						<div class="card-body">
							<h4 class="card-title" style="font-size: 20px">{{e.title}}</h4>
							<p class="card-text">{{e.paragraph}}</p>
							<a href="" class="btn btn-light" >Baca Sekarang ></a>
						</div>
					</div>
					{% endfor %}
				</div>
				<br>
				<a href="/viewmore/berita" class="btn btn-light" style="float: right">Selengkapnya ></a>
				<br>
			</div>
			<br><br>
		</div>

		<div class="program" style="background-color: #white">
			<br><br>
			<div class="container">
				<h2 style="color:#277091">PROGRAM</h2>
				<div class="card-deck">
					{% for e in progs%}

					<div class="card shadow-card" style="width:200px">
						<img class="card-img-top" src="/static/images/bencana.jpg" alt="bencana" style="width:100%">
						<div class="card-body">
							<h4 class="card-title" style="font-size: 20px">{{e.title}}</h4>
							<p class="card-text">{{e.paragraph}}</p>
							<div class="row">
								<div class="try col-sm-7">Terkumpul<br>{e.terkumpul}</div>
								<div class="try col-sm-5">Sisa Hari<br><b>9</b> hari</div>
								<a href="/crowd/donasi" class="btn btn-default">Donasi Sekarang</a>
							</div>
						</div>
					</div>
					{% endfor %}
				</div>
					
				<br>
				<a href="/viewmore/program" class="btn btn-light" style="float: right">Selangkapnya ></a>
				<br>
			</div>
			<br><br>
		</div>
		<footer>
 			{% include "footer.html" %}
 		</footer>
	</body>
</html>
<!-- 
class yang saya punya
1. head
2. berita 
-->

homePage/templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover:not(.active) {
    background-color: #111;
}

.active {
    background-color: #4CAF50;
}
</style>
</head>
<body>

<ul>
  <li><a href="#home">Home</a></li>
  <li><a href="#news">News</a></li>
  <li><a href="#contact">Contact</a></li>
  <li style="float:right"><a class="active" href="#about">About</a></li>
</ul>

</body>
</html>

viewmore/templates/footer.html
<footer class="container-fluid footer navbar-fixed-bottom" style="
background-color: #277091; 
color: white; 
padding-left:100px;
padding-right: 100px;
font-size: 25px;
font-weight: 100;
">
<br>
  <div class="row">
    <div class="col-sm-7">
      <h4><b>FUNDEE</b></h4>
    </div>
    <div class="col-sm-2.5" style="padding-top: 7px">
      <p>Our Social Media :</p>
    </div>
    <div class="col-sm">
      <a href="#" class="fa fa-facebook"></a>
      <a href="#" class="fa fa-twitter"></a>
      <a href="#" class="fa fa-google"></a>
      <a href="#" class="fa fa-linkedin"></a>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-7">
      <p> 
        <b style=" color: #69DBE2">Fundee</b> adalah platform untuk<br>
        menggalang dana dan<br>
        berdonasi secara online dan<br>
        transparan.
      </p>
    </div>
    <div class="col-sm-5.5" style="font-size: 20px; padding-top: 5px;">
      Meet our team :)<br>
      Naufaldi Athallah Rifqi as <b>CEO</b><br>
      Dimas Aditya Faiz as <b>CTO</b><br>
      Azhar Difa Arnanda as <b>FrontEnd Prgrammer</b><br>
      Faishal Ridwan as <b>BackEnd Programmer</b>
    </div>  
  </div>
  <p style="color: #69DBE2">Fakultas Ilmu Komputer<br>Universitas Indonesia</p>
  <br>
</footer>



    

viewmore/templates/htmlview.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
{% include "navbar.html" %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
    box-sizing: border-box;
}

body {
    background-color: #DBF2FF;
    padding: 20px;
    font-family: Arial;
}

/* Center website */
.main {
    max-width: 1000px;
    margin: auto;
}

h1 {
    font-size: 50px;
    word-break: break-all;
}

.row {
    margin: 10px -16px;
}

/* Add padding BETWEEN each column */
.row,
.row > .column {
    padding: 20px;
}

/* Create three equal columns that floats next to each other */
.column {
    float: left;
    width: 33.33%;
    display: none; /* Hide all elements by default */
}

/* Clear floats after rows */ 
.row:after {
    content: "";
    display: table;
    clear: both;
}

/* Content */
.content {
    background-color: white;
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    transition: 0.3s;
    padding: 0px;

}
.container {
    padding: 2px 16px;
}

/* The "show" class is added to the filtered elements */
.show {
  display: block;
}

/* Style the buttons */
.btn {
  border: none;
  outline: none;
  padding: 12px 16px;
  background-color: white;
  cursor: pointer;
}

.btn:hover {
  background-color: #ddd;
}

.btn.active {
  background-color: #666;
  color: white;
}
</style>
</head>
<body>

<!-- MAIN (Center website) -->
<div class="main">

<h1>viewmore</h1>
<hr>

<h2>Berita Terkini</h2>

<div id="myBtnContainer">
  <button class="btn active" onclick="filterSelection('all')"> Show all</button>
  <button class="btn " onclick="filterSelection('nature')"> Bencana</button>
  <button class="btn" onclick="filterSelection('cars')"> Kemanusiaan</button>
  <button class="btn" onclick="filterSelection('people')"> Bantuan</button>
</div>

<!-- Gallery Grid -->
{% for e in news%}
<div class="row ">
  <div class="column nature c">
    <div class="content">
      <img src="/static/img/01.jpg" alt="palu" style="width:100%">
      <div class="container">
        <h4>{{e.title}}</h4>
        <p>{{e.paragraph}}</p>
      </div>
    </div>
  </div>
{% endfor %}

  
<!-- END GRID -->
</div>

<!-- END MAIN -->
</div>

<script>
filterSelection("all")
function filterSelection(c) {
  var x, i;
  x = document.getElementsByClassName("column");
  if (c == "all") c = "";
  for (i = 0; i < x.length; i++) {
    w3RemoveClass(x[i], "show");
    if (x[i].className.indexOf(c) > -1) w3AddClass(x[i], "show");
  }
}

function w3AddClass(element, name) {
  var i, arr1, arr2;
  arr1 = element.className.split(" ");
  arr2 = name.split(" ");
  for (i = 0; i < arr2.length; i++) {
    if (arr1.indexOf(arr2[i]) == -1) {element.className += " " + arr2[i];}
  }
}

function w3RemoveClass(element, name) {
  var i, arr1, arr2;
  arr1 = element.className.split(" ");
  arr2 = name.split(" ");
  for (i = 0; i < arr2.length; i++) {
    while (arr1.indexOf(arr2[i]) > -1) {
      arr1.splice(arr1.indexOf(arr2[i]), 1);     
    }
  }
  element.className = arr1.join(" ");
}


// Add active class to the current button (highlight it)
var btnContainer = document.getElementById("myBtnContainer");
var btns = btnContainer.getElementsByClassName("btn");
for (var i = 0; i < btns.length; i++) {
  btns[i].addEventListener("click", function(){
    var current = document.getElementsByClassName("active");
    current[0].className = current[0].className.replace(" active", "");
    this.className += " active";
  });
}
</script>

</body>
</html>

viewmore/templates/index.html
<!doctype html>
<html lang=''>
<head>
   <meta charset='utf-8'>
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" href="styles.css">
   <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
   <script src="script.js"></script>
   <title>CSS MenuMaker</title>
</head>
<body>

<div id='cssmenu'>
<ul>
   <li class='active'><a href='#'>Fundee</a></li>
   <li><a href='#'>Berita</a></li>
   <li><a href='#'>Program</a></li>
   <li><a href='#'>Donate</a></li>
</ul>
</div>

</body>
<html>

viewmore/templates/selengkapnya.html
<!DOCTYPE html>


<html>
    <head>
        <title>
            Breaking News: Cat does not give a damn
        </title>
        <style type="text/css">

        </style>
    </head>
    <body>
        <article>
            <h1>Breaking News: Cat does not give a damn</h1>
            <p><strong>Author:</strong> Bill Clinton, <strong>Published:</strong> Yesterday</p>

            <div>
                <img src="http://peoplecancode-public.s3.amazonaws.com/cat.jpg">
                <span>Image source: The WEB</span>
            </div>

            <p>
                This paragraph will include the photo of a random cat that the author of this tutorial has found online. You can replace this text with any random text. The sole purpose of this copy is to fill the space and make sure that the image to the left has enough text to low around it. I even decided to copy the previous paragraph. This paragraph will include the photo of a random cat that the author of this tutorial has found online. You can replace this text with any random text. The sole purpose of this copy is to fill the space and make sure that the image to the left has enough text to low around it.
            </p>
            <p>This paragraph will include the photo of a random cat that the author of this tutorial has found online. You can replace this text with any random text. The sole purpose of this copy is to fill the space and make sure that the image to the left has enough text fo low around it.</p>

        </article>
    </body>
</html>